language: bash

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
      sudo: required
    - os: osx
      osx_image: xcode7.3
      sudo: required
      env:
        - OSX_BASH4=true
  
branches:
  only:
    - master
    - develop
    - /^travis.*$/

notifications:
  email: true

cache:
  directories:
        - $HOME/.composer/cache

install:
  # $MY_SHELL is path to bash executable. By default OSX has bash-3.
  # We want test m2install with bash-4 as well
  - export MY_SHELL="/bin/bash"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tests/env/osx_dependencies.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tests/env/linux_dependencies.sh; fi
  - if [[ "$OSX_BASH4" ]]; then brew install bash; export MY_SHELL="/usr/local/bin/bash"; fi
  - mysql -u root -e 'CREATE USER "travis"@"localhost";'
  - mysql -u root -e 'CREATE DATABASE travis_magento;'
  - mysql -u root -e 'GRANT ALL PRIVILEGES on travis_magento.* to "travis"@"localhost";'

#before_script:
#  - curl -Ls 'https://github.com/kward/shunit2/archive/master.zip' -o 'master.zip' && unzip -q 'master.zip' && rm 'master.zip'

script:
  - $MY_SHELL tests/functional/test-install-ee-with-quiet-mode.sh
  - $MY_SHELL tests/functional/test-restore-dumps.sh
  - $MY_SHELL tests/functional/test-restore-corrupted-dumps-missing-files.sh
